import express, { Router } from "express";
import * as paymentController from "../controllers/payment.controller";
import {
  validatePaymentConfig,
  validateMinimumAmount,
  validateMaximumAmount,
  validatePaymentRequest
} from "../middlewares/payment.middleware";
import { verifyDIDSignature } from "../middlewares/didAuth.middleware";
import {
  paymentValidators,
  vaPaymentNotificationHeaderValidators,
  vaPaymentNotificationBodyValidators,
} from "../validators/payment.validator";

const router: Router = express.Router();

/**
 * @swagger
 * tags:
 *   name: Payment
 *   description: Payment transaction management using DOKU payment gateway
 */

/**
 * @swagger
 * /payment/transaction:
 *   post:
 *     summary: Create payment transaction
 *     description: Create a new payment transaction through DOKU payment gateway
 *     tags:
 *       - Payment
 *     security:
 *       - HolderBearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - holder_did
 *               - item_ids
 *             properties:
 *               holder_did:
 *                 type: string
 *                 example: "did:example:123456789"
 *                 description: Holder's DID
 *               item_ids:
 *                 type: array
 *                 items:
 *                   type: string
 *                 example: ["item1", "item2"]
 *                 description: Array of item IDs
 *     responses:
 *       200:
 *         description: Payment transaction created successfully
 *       400:
 *         description: Invalid request data
 *       500:
 *         description: Server error
 */
router.post(
  "/transaction",
  verifyDIDSignature,
  validatePaymentConfig,
  validatePaymentRequest,
  paymentValidators,
  paymentController.createPaymentTransaction
);

/**
 * @swagger
 * /payment/test-transaction:
 *   post:
 *     summary: Create payment transaction (Test Mode)
 *     description: |
 *       Create a new payment transaction through DOKU payment gateway without DID signature verification.
 *
 *
 *       - No authentication required
 *       - Should be removed or secured in production
 *       - Use `/payment/transaction` for production with proper authentication
 *     tags:
 *       - Payment
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - holder_did
 *               - item_ids
 *             properties:
 *               holder_did:
 *                 type: string
 *                 example: "did:example:123456789"
 *                 description: Holder's DID
 *               item_ids:
 *                 type: array
 *                 items:
 *                   type: string
 *                 example: ["item1", "item2"]
 *                 description: Array of item IDs
 *     responses:
 *       200:
 *         description: Payment transaction created successfully
 *       400:
 *         description: Invalid request data
 *       500:
 *         description: Server error
 */
router.post(
  "/test-transaction",
  validatePaymentConfig,
  validatePaymentRequest,
  paymentValidators,
  paymentController.createPaymentTransaction
);

/**
 * @swagger
 * /payment/transfer-va/notification:
 *   post:
 *     summary: DOKU VA Payment Notification Webhook
 *     description: Receives payment notification from DOKU when Virtual Account payment is completed
 *     tags:
 *       - Payment
 *     parameters:
 *       - in: header
 *         name: Client-Id
 *         required: true
 *         schema:
 *           type: string
 *         description: Client ID from DOKU Back Office
 *         example: MCH-0001-10791114622547
 *       - in: header
 *         name: Request-Id
 *         required: true
 *         schema:
 *           type: string
 *         description: Unique random string (max 128 characters) generated by DOKU
 *         example: fdb69f47-96da-499d-acec-7cdc318ab2fe
 *       - in: header
 *         name: Request-Timestamp
 *         required: true
 *         schema:
 *           type: string
 *         description: Time Stamp request on UTC time in ISO8601 format
 *         example: 2020-08-11T08:45:42Z
 *       - in: header
 *         name: Signature
 *         required: true
 *         schema:
 *           type: string
 *         description: Signature to verify notification authenticity from DOKU
 *         example: HMACSHA256=1jap2tpgvWt83tG4J7IhEwUrwmMt71OaIk0oL0e6sPM=
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - partnerServiceId
 *               - customerNo
 *               - virtualAccountNo
 *               - virtualAccountName
 *               - trxId
 *               - paymentRequestId
 *               - paidAmount
 *             properties:
 *               partnerServiceId:
 *                 type: string
 *                 example: "   77777"
 *               customerNo:
 *                 type: string
 *                 example: "0000000000001"
 *               virtualAccountNo:
 *                 type: string
 *                 example: "   777770000000000001"
 *               virtualAccountName:
 *                 type: string
 *                 example: "Toru Yamashita"
 *               trxId:
 *                 type: string
 *                 example: "23219829713"
 *               paymentRequestId:
 *                 type: string
 *                 example: "12839218738127830"
 *               paidAmount:
 *                 type: object
 *                 properties:
 *                   value:
 *                     type: string
 *                     example: "11500.00"
 *                   currency:
 *                     type: string
 *                     example: "IDR"
 *               virtualAccountEmail:
 *                 type: string
 *                 example: "toru@oor.com"
 *               virtualAccountPhone:
 *                 type: string
 *                 example: "081293912081"
 *     responses:
 *       200:
 *         description: Payment notification processed successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 responseCode:
 *                   type: string
 *                   example: "2002500"
 *                 responseMessage:
 *                   type: string
 *                   example: "Success"
 *                 virtualAccountData:
 *                   type: object
 *       400:
 *         description: Bad Request
 *       403:
 *         description: Forbidden
 *       500:
 *         description: Internal server error
 */
router.post(
  "/transfer-va/notification",
  vaPaymentNotificationHeaderValidators,
  vaPaymentNotificationBodyValidators,
  paymentController.handleVAPaymentNotification
);

export default router;