-- CreateEnum
CREATE TYPE "VCResponseStatus" AS ENUM ('PENDING', 'PROCESSING', 'CLAIMED');

-- AlterTable
ALTER TABLE "VCResponse" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "status" "VCResponseStatus" NOT NULL DEFAULT 'PENDING',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
